### ISSUE TITLE
Driver for Linux Kernel 5.13.x?

### ISSUE THREAD

**Issue by matthesinator** [nodemcu/nodemcu-devkit#20]
Hi!
Does someone have the driver for newer Linux Kernels? Thanks!

**Comment by SeaGull711** [comment]
Looking for the same!

**Comment by matthesinator** [comment]
@SeaGull711 For me it was actually a different problem, although I forgot to close this issue. But I'll use the chance to share what I found:

I followed [this](https://github.com/juliagoda/CH341SER) to install the driver, which I don't know if it was necessary but it works now. BUT there was some weird braille display driver named [BRLTTY](https://brltty.app/) which somehow hijacked the port or something. Couldn't uninstall it because it was a dependency for something, which I still don't understand. Anyway, I found [this on stackoverflow](https://unix.stackexchange.com/questions/670636/unable-to-use-usb-dongle-based-on-usb-serial-converter-chip/) to disable that driver, and that got it working.

[Reddit thread I opened](https://www.reddit.com/r/microcontrollers/comments/qi8hip/ch34x_drivers_for_linux_kernel_5x/)
