### ISSUE TITLE
Install fails on m1 mac version 13.0

### ISSUE THREAD

**Issue by mo7alb** [nodemcu/nodemcu-devkit#21]
I am trying to install the mac drivers on an m1 macbook air. It gives me an error saying its incompatible with mac version
<img width="618" alt="Screenshot 2022-11-02 at 12 09 21 PM" src="https://user-images.githubusercontent.com/41588283/199434446-c03d13f5-55f2-472e-b912-f33d0b16fa4d.png">

**Comment by JxxIT** [comment]
Yes, i have this problem too.
