### ISSUE TITLE
Impossible to flash/connect

### ISSUE THREAD

**Issue by RataDP** [nodemcu/nodemcu-devkit#8]
I'm having troubles to flash or connect my _devkit v1_. It arrived my home 2 days ago and I was not able to flash it or at least communicate with it.

I'm going to describe my case. I connect my _devkit v1_ via USB to microUSB with the CP2102 USBtoUARP, then the blue led of the ESP8266 blinks twice and stop. After this I can see the SSID "AI_THINKER_DA7E19" and connect to it, I got a 192.168.4.2 and the device .1. It answers to the ping but there is not webserver. Now I try to flash it, first I tried with Linux and ESPTool,

``` 
# python2 esptool.py --port /dev/ttyUSB0 write_flash 0x00000 firmware.bin
Connecting...

A fatal error occurred: Failed to connect to ESP8266
```

Well I read somewhere it could be a bug with ESPtool with high values of baudrate, so I tried with `--baud 9600` but the same output also with different baudrates. Meanwhile the program is in the state `connecting...`, the blue led blinks. I tried to reset with the Flash button pressed and the same result, nothing change. Also I tried wiring the GPIO0 to GND but still the same error.

Now it is the turn for Windows, I tried with the nodemcu-flasher, the driver was correctly install and the port is assigned correctly too. Select the COM port and set the baudrate to 9600 and flash. The log says `Begin to find ESP8266` enters in a loop and the blue led blinks every 1/2 seconds. Just to point it out, in the tab *operation* not appears any mac, it says "Waiting...". Just like before I changed the Baudrate and I tried all of them but nothing happens. _(I also press flash and reset like before but nothing)_

After all this troubles I tried to communicate with the devkit via Serial port with putty and Screen. The connection seems to be established but nothing appears in it. Pressing RST it should write something... garbage or some characters but nothing.

I don't know if I'm doing something wrong or the devkit it's broken. Some solution or tip?

Thank you

**Comment by mrmonteith** [comment]
I'm trying to remember when I first tried this.  I think I used the flasher tool.  You start the attempt at transfer, hold down the reset and flasher button, release the flasher button and then about a half second or so after release the reset.   I don't have my device in front of me to check.  Of course I only had to do it one time and I've had mine for about month.  Hope it helps anyway.

**Comment by RataDP** [comment]
Did not work :S

I put it in the wrong repository and I move it to the correct one.

Thanks for the help @mrmonteith I c&p on the other post too.
