### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MishraShivendra** [nodemcu/nodemcu-devkit#9]
I am wondering, How is this picture useful to a developer?
https://github.com/nodemcu/nodemcu-devkit/blob/master/Documents/NodeMCU_DEVKIT_V0.9.png

**Comment by mrmonteith** [comment]
Lots of reasons.  Sometimes it's for comparison to make sure you using the same device and not a knockoff.  It might be someone is interested in one and stumbled across this and didn't know what one looked like. I always have these type pics around for better clarity of pinouts.    Regardless of the reason I'd rather have too much information than not enough.

**Comment by MishraShivendra** [comment]
I wish If there would be a better documentation about dev-kit. Something like detailed data-sheet(in English). If one has dev-kit. Probably he can see it in his hands and might not like to refer that picture. (Just a suggestion-Never mind)

**Comment by mrmonteith** [comment]
I tend to agree there.  I've depended on pinout, Wiki pages, and general information on ESP8266 to get what I needed.  
http://www.esp8266.com/wiki/doku.php?id=nodemcu#devkit_09
 Then I usually refer to the datasheets for the ESP8266.   It would be nice to compile that as it relates to the NodeMCU.
